repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      # Corrige errores de lint automáticamente
      - id: ruff
        args: [--fix]
      # Formatea el código
      - id: ruff-format
