"""adjuster_positions_with_fk

Revision ID: e7c681c66318
Revises: ea7904e1226e
Create Date: 2026-03-19 19:58:40.467925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'e7c681c66318'
down_revision: Union[str, None] = 'ea7904e1226e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('adjuster_positions',
    sa.Column('adjuster_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('h3_r8', sa.String(length=20), nullable=True),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=True),
    sa.Column('gap_index', sa.Float(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('hora_num', sa.Integer(), nullable=True),
    sa.Column('dia_semana_num', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adjuster_id'], ['adjusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adjuster_positions_adjuster_id', 'adjuster_positions', ['adjuster_id'], unique=False)
    op.create_index('idx_adjuster_positions_h3_r8', 'adjuster_positions', ['h3_r8'], unique=False)
    op.create_geospatial_index('idx_adjuster_positions_location', 'adjuster_positions', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_adjuster_positions_scenario', 'adjuster_positions', ['scenario'], unique=False)
    op.alter_column('demand_predictions', 'model_version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demand_predictions', 'model_version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'v1.0.0'::character varying"),
               existing_nullable=False)
    op.drop_index('idx_adjuster_positions_scenario', table_name='adjuster_positions')
    op.drop_geospatial_index('idx_adjuster_positions_location', table_name='adjuster_positions', postgresql_using='gist', column_name='location')
    op.drop_index('idx_adjuster_positions_h3_r8', table_name='adjuster_positions')
    op.drop_index('idx_adjuster_positions_adjuster_id', table_name='adjuster_positions')
    op.drop_geospatial_table('adjuster_positions')
    # ### end Alembic commands ###
