"""initial_schema

Revision ID: 25b52c0f9f8b
Revises: 
Create Date: 2026-03-04 12:47:08.010096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25b52c0f9f8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('adjusters',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('home_latitude', sa.Float(), nullable=False),
    sa.Column('home_longitude', sa.Float(), nullable=False),
    sa.Column('home_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('max_cases_per_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_geospatial_index('idx_adjusters_home_location', 'adjusters', ['home_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_adjusters_external_id'), 'adjusters', ['external_id'], unique=True)
    op.create_geospatial_table('incidents',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('incident_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_incidents_location', 'incidents', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_incidents_external_id'), 'incidents', ['external_id'], unique=True)
    op.create_table('assignments',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('adjuster_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('travel_time_minutes', sa.Integer(), nullable=True),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adjuster_id'], ['adjusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_adjuster_id'), 'assignments', ['adjuster_id'], unique=False)
    op.create_index(op.f('ix_assignments_incident_id'), 'assignments', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_incident_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_adjuster_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_incidents_external_id'), table_name='incidents')
    op.drop_geospatial_index('idx_incidents_location', table_name='incidents', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('incidents')
    op.drop_index(op.f('ix_adjusters_external_id'), table_name='adjusters')
    op.drop_geospatial_index('idx_adjusters_home_location', table_name='adjusters', postgresql_using='gist', column_name='home_location')
    op.drop_geospatial_table('adjusters')
    # ### end Alembic commands ###
